openapi: "3.0.2"
info:
  title: "P2P地震情報 API仕様書"
  version: "0.1.0"
servers:
  - url: https://api.p2pquake.net/v2
paths:
  /jma/quake:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 地震情報リスト
      description: |
        地震情報を返却します。デフォルトは新しい順に最大10件です。
        データは2015年1月10日から提供しています。
      responses:
        200:
          description: 地震情報リスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMAQuakes'
        400:
          description: パラメタに誤りがあります
    parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/order'
      - $ref: '#/components/parameters/sinceDate'
      - $ref: '#/components/parameters/untilDate'
      - $ref: '#/components/parameters/quakeType'
      - $ref: '#/components/parameters/minMagnitude'
      - $ref: '#/components/parameters/maxMagnitude'
      - $ref: '#/components/parameters/minScale'
      - $ref: '#/components/parameters/maxScale'
      - $ref: '#/components/parameters/prefecture'
  /jma/quake/{id}:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 地震情報
      responses:
        200:
          description: 指定したIDの地震情報を返却します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMAQuake'
        400:
          description: IDの形式が間違っています
        404:
          description: 指定IDの情報が見つかりません
    parameters:
      - $ref: '#/components/parameters/id'
  /jma/tsunami:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 津波予報リスト
      description: |
        津波予報を返却します。デフォルトは新しい順に最大10件です。
        データは2016年11月22日から提供しています。
      responses:
        200:
          description: 津波予報リスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMATsunamis'
        400:
          description: パラメタに誤りがあります
    parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/order'
      - $ref: '#/components/parameters/sinceDate'
      - $ref: '#/components/parameters/untilDate'
  /jma/tsunami/{id}:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 津波予報
      responses:
        200:
          description: 指定したIDの津波予報を返却します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMATsunami'
        400:
          description: IDの形式が間違っています
        404:
          description: 指定IDの情報が見つかりません
    parameters:
      - $ref: '#/components/parameters/id'
  /history:
    get:
      tags:
        - P2P地震情報 JSON API
      summary: 履歴API
      responses:
        200:
          description: TODO
  /ws:
    get:
      tags:
        - P2P地震情報 リアルタイムAPI
      summary: WebSocket
      responses:
        default:
          description: TODO
components:
  parameters:
    offset:
      name: offset
      in: query
      required: false
      description: 読み飛ばす件数 (デフォルトは0)。例えば、 limit=100&offset=200 とすると、201件目から100件を返却します。
      schema:
        type: string
    limit:
      name: limit
      in: query
      required: false
      description: 返却件数（デフォルトは10）
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
    quakeType:
      name: types[]
      in: query
      required: false
      description: 地震情報の種類
      schema:
        type: array
        items:
          type: string
          enum: 
            - ScalePrompt(震度速報)
            - Destination(震源に関する情報)
            - ScaleAndDestination(震度・震源に関する情報)
            - DetailScale(各地の震度に関する情報)
            - Foreign(遠地地震に関する情報)
            - Other(その他の情報)
    minScale:
      name: min_scale
      in: query
      required: false
      description: 最大震度の下限
      schema:
        type: integer
        format: int32
        enum:
          - 10(震度1)
          - 20(震度2)
          - 30(震度3)
          - 40(震度4)
          - 45(震度5弱)
          - 50(震度5強)
          - 55(震度6弱)
          - 60(震度6強)
          - 70(震度7)
    maxScale:
      name: max_scale
      in: query
      required: false
      description: 最大震度の上限
      schema:
        type: integer
        format: int32
        enum:
          - 10(震度1)
          - 20(震度2)
          - 30(震度3)
          - 40(震度4)
          - 45(震度5弱)
          - 50(震度5強)
          - 55(震度6弱)
          - 60(震度6強)
          - 70(震度7)
    prefecture:
      name: prefectures[]
      in: query
      required: false
      description: 各都道府県の最低震度
      schema:
        type: array
        items:
          type: object
    minMagnitude:
      name: min_magnitude
      in: query
      required: false
      description: マグニチュード下限
      schema:
        type: number
    maxMagnitude:
      name: max_magnitude
      in: query
      required: false
      description: マグニチュード上限
      schema:
        type: number
    sinceDate:
      name: since_date
      in: query
      required: false
      description: 指定日かそれ以降 (yyyyMMdd形式)
      schema:
        type: string
    untilDate:
      name: until_date
      in: query
      required: false
      description: 指定日かそれ以前 (yyyyMMdd形式)
      schema:
        type: string
    order:
      name: order
      in: query
      description: 並び順
      schema:
        type: integer
        format: int32
        enum:
          - 1 (昇順、古い順)
          - -1 (降順、新しい順)
    id:
      name: id
      in: query
      description: ID
      schema:
        type: string
  schemas:
    JMAQuake:
      type: object
    JMAQuakes:
      type: array
      items:
        $ref: '#/components/schemas/JMAQuake'
    JMATsunami:
      type: object
    JMATsunamis:
      type: array
      items:
        $ref: '#/components/schemas/JMATsunami'
