openapi: "3.0.2"
info:
  title: "P2P地震情報 API仕様書"
  version: "2.0.0"
  description: "[気象庁 | 著作権・リンク・個人情報保護について](http://www.jma.go.jp/jma/kishou/info/coment.html)に従い、気象庁が発表した地震情報・津波予報を一部加工して提供しています。<br>本APIは、気象庁 利用規約に従っていれば、商用・非商用問わず自由にご利用いただいて構いません。"
servers:
  - url: https://api.p2pquake.net/v2
paths:
  /jma/quake:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 地震情報リスト
      description: |
        地震情報を返却します。デフォルトは新しい順に最大10件です。
        データは2015年1月10日から提供しています。
      responses:
        200:
          description: 地震情報リスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMAQuakes'
        400:
          description: パラメタに誤りがあります
    parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/order'
      - $ref: '#/components/parameters/sinceDate'
      - $ref: '#/components/parameters/untilDate'
      - $ref: '#/components/parameters/quakeType'
      - $ref: '#/components/parameters/minMagnitude'
      - $ref: '#/components/parameters/maxMagnitude'
      - $ref: '#/components/parameters/minScale'
      - $ref: '#/components/parameters/maxScale'
      - $ref: '#/components/parameters/prefecture'
  /jma/quake/{id}:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 地震情報
      responses:
        200:
          description: 指定したIDの地震情報を返却します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMAQuake'
        400:
          description: IDの形式が間違っています
        404:
          description: 指定IDの情報が見つかりません
    parameters:
      - $ref: '#/components/parameters/id'
  /jma/tsunami:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 津波予報リスト
      description: |
        津波予報を返却します。デフォルトは新しい順に最大10件です。
        データは2016年11月22日から提供しています。
      responses:
        200:
          description: 津波予報リスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMATsunamis'
        400:
          description: パラメタに誤りがあります
    parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/order'
      - $ref: '#/components/parameters/sinceDate'
      - $ref: '#/components/parameters/untilDate'
  /jma/tsunami/{id}:
    get:
      tags:
        - 気象庁 地震情報・津波予報 JSON API
      summary: 津波予報
      responses:
        200:
          description: 指定したIDの津波予報を返却します。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JMATsunami'
        400:
          description: IDの形式が間違っています
        404:
          description: 指定IDの情報が見つかりません
    parameters:
      - $ref: '#/components/parameters/id'
  /ws:
    get:
      tags:
        - P2P地震情報 API (未実装)
      summary: P2P地震情報 WebSocket API
      description: |
        P2P地震情報の各種情報をリアルタイムに配信します。 WebSocket プロトコルでの接続が必要です。
      responses:
        101:
          description: WebSocket 接続に切り替わります。
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/WebSocketAPI'
  /history:
    get:
      tags:
        - P2P地震情報 API (未実装)
      summary: P2P地震情報 JSON API (v2)
      description: |
        P2P地震情報の各種情報を返却します。  
        未実装: [JSON API v1](https://www.p2pquake.net/dev/json-api/) をご利用ください。
      responses:
        200:
          description: 各種情報を返却します。
components:
  parameters:
    offset:
      name: offset
      in: query
      required: false
      description: 読み飛ばす件数 (0以上、デフォルトは0)。例えば、 limit=100&offset=200 とすると、201件目から100件を返却します。
      schema:
        type: integer
        format: int32
        minimum: 0
    limit:
      name: limit
      in: query
      required: false
      description: 返却件数 (1〜100、デフォルトは10)
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
    quakeType:
      name: quake_type
      in: query
      required: false
      description: 地震情報の種類。値はScalePrompt(震度速報)、Destination(震源に関する情報)、ScaleAndDestination(震度・震源に関する情報)、DetailScale(各地の震度に関する情報)、Foreign(遠地地震に関する情報)、Other(その他の情報)です。
      schema:
        type: string
        enum:
          - ScalePrompt
          - Destination
          - ScaleAndDestination
          - DetailScale
          - Foreign
          - Other
    minScale:
      name: min_scale
      in: query
      required: false
      description: 最大震度の下限。値は10(震度1)、20(震度2)、30(震度3)、40(震度4)、45(震度5弱)、50(震度5強)、55(震度6弱)、60(震度6強)、70(震度7)です。
      schema:
        type: integer
        format: int32
        enum:
          - 10
          - 20
          - 30
          - 40
          - 45
          - 50
          - 55
          - 60
          - 70
    maxScale:
      name: max_scale
      in: query
      required: false
      description: 最大震度の上限。値は10(震度1)、20(震度2)、30(震度3)、40(震度4)、45(震度5弱)、50(震度5強)、55(震度6弱)、60(震度6強)、70(震度7)です。
      schema:
        type: integer
        format: int32
        enum:
          - 10
          - 20
          - 30
          - 40
          - 45
          - 50
          - 55
          - 60
          - 70
    prefecture:
      name: prefectures[]
      in: query
      required: false
      description: 各都道府県の最低震度。 "兵庫県,10" のように指定します。
      schema:
        type: array
        items:
          type: object
    minMagnitude:
      name: min_magnitude
      in: query
      required: false
      description: マグニチュード下限
      schema:
        type: number
    maxMagnitude:
      name: max_magnitude
      in: query
      required: false
      description: マグニチュード上限
      schema:
        type: number
    sinceDate:
      name: since_date
      in: query
      required: false
      description: 指定日かそれ以降 (yyyyMMdd形式)
      schema:
        type: string
        pattern: \d{8}
    untilDate:
      name: until_date
      in: query
      required: false
      description: 指定日かそれ以前 (yyyyMMdd形式)
      schema:
        type: string
        pattern: \d{8}
    order:
      name: order
      in: query
      description: 並び順。1は昇順（古い順）、-1は降順（新しい順）です。デフォルトは降順。
      schema:
        type: integer
        format: int32
        enum:
          - 1
          - -1
    id:
      name: id
      in: path
      required: true
      description: ID
      schema:
        type: string
  schemas:
    JMAQuake:
      type: object
      description: 地震情報
      required:
        - id
        - code
        - issue
        - earthquake
      properties:
        id:
          type: string
          description: 情報を一意に識別するID
        code:
          type: integer
          format: int32
          description: 情報コード。常に551です。
        issue:
          type: object
          description: 発表元の情報
          required:
            - time
            - type
          properties:
            source:
              type: string
              description: 発表元
            time:
              type: string
              description: 発表日時
            type:
              type: string
              description: 発表種類
              enum:
                - ScalePrompt(震度速報)
                - Destination(震源に関する情報)
                - ScaleAndDestination(震度・震源に関する情報)
                - DetailScale(各地の震度に関する情報)
                - Foreign(遠地地震に関する情報)
                - Other(その他の情報)
            correct:
              type: string
              description: 訂正の有無
              enum:
                - None(なし)
                - Unknown(不明)
                - ScaleOnly(震度)
                - DestinationOnly(震源)
                - ScaleAndDestination(震度・震源)
        earthquake:
          type: object
          required:
            - time
          properties:
            time:
              type: string
              description: 発生日時
            hypocenter:
              type: object
              description: 震源情報
              properties:
                name:
                  type: string
                  description: 名称
                latitude:
                  type: number
                  description: 緯度。震源情報が存在しない場合は-200となります。
                longitude:
                  type: number
                  description: 経度。震源情報が存在しない場合は-200となります。
                depth:
                  type: integer
                  format: int32
                  description: 深さ(km)。「ごく浅い」は0、震源情報が存在しない場合は-1となります。
                magnitude:
                  type: number
                  description: マグニチュード。震源情報が存在しない場合は-1となります。
            maxScale:
              type: integer
              format: int32
              description: 最大震度。震度情報が存在しない場合は-1となります。
              enum:
                - -1(震度情報なし)
                - 10(震度1)
                - 20(震度2)
                - 30(震度3)
                - 40(震度4)
                - 45(震度5弱)
                - 50(震度5強)
                - 55(震度6弱)
                - 60(震度6強)
                - 70(震度7)
            domesticTsunami:
              type: string
              description: 国内への津波の有無
              enum:
                - None(なし)
                - Unknown(不明)
                - Checking(調査中)
                - NonEffective(若干の海面変動が予想されるが、被害の心配なし)
                - Watch(津波注意報)
                - Warning(津波予報(種類不明))
            foreignTsunami:
              type: string
              description: 海外での津波の有無
              enum:
                - None(なし)
                - Unknown(不明)
                - Checking(調査中)
                - NonEffectiveNearby(震源の近傍で小さな津波の可能性があるが、被害の心配なし)
                - WarningNearby(震源の近傍で津波の可能性がある)
                - WarningPacific(太平洋で津波の可能性がある)
                - WarningPacificWide(太平洋の広域で津波の可能性がある)
                - WarningIndian(インド洋で津波の可能性がある)
                - WarningIndianWide(インド洋の広域で津波の可能性がある)
                - Potential(一般にこの規模では津波の可能性がある)
        points:
          type: array
          description: 震度観測点の情報
          items:
            type: object
            required:
              - pref
              - addr
              - isArea
              - scale
            properties:
              pref:
                type: string
                description: 都道府県
              addr:
                type: string
                description: 震度観測点名称（震度速報の場合は [気象庁 | 緊急地震速報や震度情報で用いる区域の名称](http://www.data.jma.go.jp/svd/eqev/data/joho/shindo-name.html) に記載のある区域名）
              isArea:
                type: boolean
                description: 区域名かどうか
              scale:
                type: number
                description: 震度
                enum:
                  - 10(震度1)
                  - 20(震度2)
                  - 30(震度3)
                  - 40(震度4)
                  - 45(震度5弱)
                  - 46(震度5弱以上と推定されるが震度情報を入手していない)
                  - 50(震度5強)
                  - 55(震度6弱)
                  - 60(震度6強)
                  - 70(震度7)
      example:
        issue:
          source: 気象庁
          time: 2019/08/26 20:57:00
          correct: None
          type: DetailScale
        earthquake:
          domesticTsunami: None
          foreignTsunami: Unknown
          hypocenter:
            depth: 50
            latitude: 24.4
            longitude: 125.2
            magnitude: 4.0
            name: 宮古島近海
          maxScale: 10
          time: 2019/08/26 20:53:00
        points:
          - addr: 宮古島市城辺福北
            isArea: false
            pref: 沖縄県
            scale: 10
          - addr: 宮古島市伊良部長浜
            isArea: false
            pref: 沖縄県
            scale: 10
    JMAQuakes:
      type: array
      items:
        $ref: '#/components/schemas/JMAQuake'
    JMATsunami:
      type: object
      description: 津波予報
      required:
        - id
        - code
        - cancelled
        - issue
      properties:
        id:
          type: string
          description: 情報を一意に識別するID
        code:
          type: integer
          format: int32
          description: 情報コード。常に552です。
        cancelled:
          type: boolean
          description: 津波予報が解除されたかどうか。trueの場合、areasは空配列です。
        issue:
          type: object
          description: 発表元の情報
          required:
            - source
            - time
            - type
          properties:
            source:
              type: string
              description: 発表元
            time:
              type: string
              description: 発表日時
            type:
              type: string
              description: 発表種類。現在は Focus (津波予報) のみです。
        areas:
          type: array
          description: 津波予報の詳細
          items:
            type: object
            properties:
              grade:
                type: string
                description: 津波予報の種類
                enum:
                  - MajorWarning (大津波警報)
                  - Warning (津波警報)
                  - Watch (津波注意報)
                  - Unknown (不明)
              immediate:
                type: boolean
                description: 直ちに津波が来襲すると予想されているかどうか
              name:
                type: string
                description: 津波予報区名。[気象庁｜津波予報区について](http://www.data.jma.go.jp/svd/eqev/data/joho/t-yohokuinfo.html)を参照。
      example:
        code: 552
        cancelled: false
        issue:
          source: 気象庁
          time: "2019/06/18 22:24:00"
          type: "Focus"
        areas:
          - grade: Warning
            immediate: true
            name: 福島県
          - grade: Watch
            immediate: false
            name: 青森県太平洋沿岸
    JMATsunamis:
      type: array
      items:
        $ref: '#/components/schemas/JMATsunami'
    Userquake:
      type: object
      description: 地震感知情報の評価結果です。
      properties:
        id:
          type: string
          description: 情報を一意に識別するID
        code:
          type: integer
          format: int32
          description: 情報コード。常に561です。
        time:
          type: string
          description: 受信日時。形式は `2006/01/02 15:04:05.999` です。
        area:
          type: integer
          format: int32
          description: 地域コード
    Areapeers:
      type: object
      description: P2P地震情報ネットワークに接続しているピアの地域分布です。
    EEWDetection:
      type: object
      description: 緊急地震速報の発表検出です。
      properties:
        id:
          type: string
          description: 情報を一意に識別するID
        code:
          type: integer
          format: int32
          description: 情報コード。常に554です。
        time:
          type: string
          description: 受信日時。形式は `2006/01/02 15:04:05.999` です。
        type:
          type: string
          description: 検出種類
          enum:
            - "\"Full\" (チャイム＋音声)"
            - "\"Chime\" (チャイム (未実装))"
    UserquakeEvaluation:
      type: object
      description: 地震感知情報の評価結果です。
      properties:
        id:
          type: string
          description: 情報を一意に識別するID
        code:
          type: integer
          format: int32
          description: 情報コード。常に9611です。
        count:
          type: integer
          format: int32
          description: 件数
        confidence:
          type: number
          description: |
            P2P地震情報 Beta3 における信頼度。  
            0: 非表示、0.97015: レベル1、0.96774: レベル2、0.97024: レベル3、0.98052: レベル4。  
            値は適合率 (precision) です。
        started_at:
          type: string
          description: |
            開始日時。地震感知情報のイベントを一意に識別するキーとなります。
            形式は `2006/01/02 15:04:05.999` です。
        updated_at:
          type: string
          description: 更新日時。形式は `2006/01/02 15:04:05.999` です。
        time:
          type: string
          description: 評価日時。形式は `2006/01/02 15:04:05.999` です。
        area_confidences:
          type: object
          description: 地域ごとの信頼度情報
          properties:
            nnn:
              type: object
              description: キーは地域コードです。
              properties:
                confidence:
                  type: number
                  description: |
                    信頼度  
                    P2P地震情報 Beta3 においては、 0未満: F、0.0以上0.2未満: E、0.2以上0.4未満: D、0.4以上0.6未満: C、0.6以上0.8未満: B、0.8以上: A です。
                count:
                  type: integer
                  format: int32
                  description: 件数
                display:
                  type: string
                  description: P2P地震情報 Beta3 における信頼度表示