name: Build Docker

on: [push, pull_request]

env:
  IMAGE_NAME: p2pquake/web-api-v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile

